print("Plik a - zmiana 1")
print("Plik a - zmiana 2 ale nagla")
print("Plik a - zmiana 3 inny branch")
print("Plik a - zmiana pull")
print("Plik a - zmian psuh")
print("Plik a - zmiana na remote branch")
